### ISSUE TITLE
Failed to load plugin "gamified-pkm"

### ISSUE THREAD

**Issue by lulunac27a** [saertna/obsidian-gamified-pkm#77]
When I update Obsidian to version 1.7, the plugin failed to load, but the plugin were loaded successfully before version 1.7.

**Comment by saertna** [comment]
Thanks @lulunac27a, I'm on it.

**Comment by saertna** [comment]
@lulunac27a , can you confirm the plugin is loading successful when deactivating and activating it after obsidian start? This is working as a workaround on my side. Would be good to see a confirmation if it's for you the same or if you see another behaviour.

**Comment by lulunac27a** [comment]
It works when I turn off the plugin, restart Obsidian, and turn the plugin back on, but when I restart Obsidian again with the plugin turned on, the plugin fails to load.
